<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test _Suite _lab2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b5d4f29d-d5a9-4a43-b6a1-2cd02ceebf6f</testSuiteGuid>
   <testCaseLink>
      <guid>bc0cee71-ec8c-4de7-a7b5-7617ce39bea9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lab_1_2/Test1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61bde7ec-1195-4e4f-8826-719ea3007417</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97473723-42cf-4be7-91db-640301bf2095</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cd6cee5-4f2d-4ead-8efb-44b9b0c0007f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d09edd0f-7dc1-49d8-8857-6c836673e91e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lab_1_2/Test2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d201d3f7-fb96-44cf-bb38-2b48e2104c40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5cc4b25-2824-4009-9d4d-ab8d9a68a0e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1270d2c3-4513-49c0-ad1d-085a4f498fd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc561fd6-d6f9-4c57-a5c5-1c9949608ce5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lab_1_2/Test3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5159995-6aeb-4d1d-8dfb-4ea0930c1dfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aa72601-b89a-403c-83d0-4e93ae64dda0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04553f12-06e9-473e-977f-a9302b47f0bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ed9aa95-8fab-4747-b06e-ba3e8dc9bf52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lab_1_2/Test4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c42d7844-30ef-4597-beb1-9f2e461f1a10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4791ed3f-3e32-4517-837e-07a3e911135b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f16d714-776a-4c01-9f14-1a1184073825</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d33d78e6-a849-43a3-8c7e-9077a38c65d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Lab_1_2/Test5</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e3e550f-7f2d-445c-b79e-b30458086bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88e74d70-2c4b-4c73-a84b-507b1a51812f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fcbab4f-560f-4431-af79-9994912fb526</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
